# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20161011_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='custom_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='custom_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
