# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_boardpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpage',
            name='available_tags',
        ),
        migrations.RemoveField(
            model_name='boardpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='boardpage',
            name='peoplepage_ptr',
            field=models.OneToOneField(auto_created=True, default=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.PeoplePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='board_member',
            field=models.BooleanField(default=False),
        ),
    ]
