# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20160913_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='board_member',
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
