# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('common', '0009_auto_20160913_1736'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='boardpage',
        #     name='page_ptr',
        # ),
        migrations.RemoveField(
            model_name='boardpage',
            name='peoplepage_ptr',
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='style_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taggit.Tag'),
        ),
        migrations.DeleteModel(
            name='BoardPage',
        ),
    ]
