# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('common', '0011_remove_peoplepage_style_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='style_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taggit.Tag'),
        ),
    ]
