# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_peoplepage_style_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepage',
            name='style_list',
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='display_style',
            field=models.CharField(choices=[('concise', 'Concise Style'), ('detail', 'Detailed Style')], default=1, max_length=16, verbose_name='display style'),
            preserve_default=False,
        ),
    ]
