# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20161013_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
    ]
