# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20161012_1628'),
        ('common', '0014_remove_person_title'),
        ('common', '0002_auto_20161013_1518'),
    ]

    operations = [
    ]
