# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20160914_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepage',
            name='display_style',
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='statement',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='subtitle',
            field=models.CharField(default='untitled', max_length=30),
        ),
    ]
