# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('common', '0016_auto_20161014_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpImagePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upImagePath', models.CharField(help_text='Up image path', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
