# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 19:29
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_peoplepage_display_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='other_info',
            field=wagtail.wagtailcore.fields.StreamField((('position', wagtail.wagtailcore.blocks.TextBlock(max_legnth=140)), ('term', wagtail.wagtailcore.blocks.TextBlock(max_length=9)), ('linked_in', wagtail.wagtailcore.blocks.URLBlock()), ('blog', wagtail.wagtailcore.blocks.PageChooserBlock()), ('osf_profile', wagtail.wagtailcore.blocks.URLBlock()), ('phone_number', wagtail.wagtailcore.blocks.IntegerBlock(max_value=9999999999, min_value=0)), ('email_address', wagtail.wagtailcore.blocks.EmailBlock()), ('title', wagtail.wagtailcore.blocks.TextBlock(max_length=140)), ('fave_food', wagtail.wagtailcore.blocks.TextBlock(max_length=45)))),
        ),
    ]
