# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20160915_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.AlterField(
            model_name='persontag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_person', to='common.Person'),
        ),
    ]
