# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_merge_20161017_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='action',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
