# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20160916_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=wagtail.wagtailcore.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
