# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_person_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
