# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20160916_1435'),
        ('common', '0011_auto_20160916_1923'),
    ]

    operations = [
    ]
