# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20161017_1849'),
        ('common', '0021_auto_20161017_1734'),
    ]

    operations = [
    ]
