# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('common', '0025_auto_20161018_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionedRedirect',
            fields=[
                ('versioned_redirect_page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versioned_redirects', to='wagtailcore.Page', verbose_name='redirect to a page')),
            ],
            bases=('wagtailredirects.redirect',),
        ),
        migrations.AddField(
            model_name='versionedredirect',
            name='redirect_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailredirects.Redirect'),
            preserve_default=False,
        ),
    ]
