# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_versionedredirect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('have_adopted', models.BooleanField(help_text='whether it has adopted registered reports')),
                ('have_issues', models.BooleanField(help_text='whether it has special issues')),
                ('have_features', models.BooleanField(help_text='whether it has features')),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('society', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=255)),
                ('note', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Journals',
            },
            bases=(models.Model, wagtail.wagtailsearch.index.Indexed),
        ),
    ]
