# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20160921_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='news_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='intro',
            field=models.CharField(max_length=255),
        ),
    ]
