# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('common', '0026_versionedredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionedredirect',
            name='redirect_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailredirects.Redirect'),
            preserve_default=False,
        ),
    ]
