# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20161025_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='is_eligible_journal',
        ),
        migrations.AddField(
            model_name='journal',
            name='is_top_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_featured_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_preregistered_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_registered_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_special_journal',
            field=models.BooleanField(default=False),
        ),
    ]
