# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20160921_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsindexpage',
            old_name='intro',
            new_name='statement',
        ),
    ]
