# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_organization_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='class_choice',
        ),
        migrations.AddField(
            model_name='journal',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='association',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_featured_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_preregistered_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_registered_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_special_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='is_top_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='journal',
            name='additional',
            field=wagtail.wagtailcore.fields.StreamField((('journal', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('note', wagtail.wagtailcore.blocks.RawHTMLBlock())), blank=True, null=True),
        ),
    ]
