# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_auto_20161026_2028'),
        ('common', '0031_organization_pattern'),
    ]

    operations = [
    ]
