# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_organization_pattern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='pattern',
            new_name='partner',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='additional',
        ),
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=wagtail.wagtailcore.fields.StreamField((('note', wagtail.wagtailcore.blocks.StructBlock((('description', wagtail.wagtailcore.blocks.CharBlock(max_length=255, required=False)), ('link', wagtail.wagtailcore.blocks.URLBlock(required=False))))),), blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
