# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20160922_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsindexpage',
            name='statement',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
