# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20160922_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='external_link',
            field=models.CharField(blank=True, help_text='External Article Link', max_length=255),
        ),
    ]
