# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_merge_20161026_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
