# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_newsarticle_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='external_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='External Article Link'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
