# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_auto_20161101_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='google_plus',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
