# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_auto_20161101_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='InkindDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('thank_you_message', models.TextField()),
                ('organization', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inkind_donations', to='common.Organization', verbose_name='Organization')),
            ],
            options={
                'ordering': ['date'],
            },
            bases=(models.Model, wagtail.wagtailsearch.index.Indexed),
        ),
    ]
