# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_inkinddonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
