# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0048_auto_20170111_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_top_signatory',
            field=models.BooleanField(default=False),
        ),
    ]
