# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0051_import_2000_top_journals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionedredirect',
            name='redirect_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='wagtailredirects.Redirect'
            ),
        ),
    ]


migrations.AddField(
    model_name='versionedredirect',
    name='redirect_ptr',
    field=models.OneToOneField(
        auto_created=True,
        default=1,
        on_delete=django.db.models.deletion.CASCADE,
        parent_link=True,
        primary_key=True,
        serialize=False,
        to='wagtailredirects.Redirect'),
    preserve_default=False,
),
