# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-21 13:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0052_auto_20170331_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applying',
            field=wagtail.wagtailcore.fields.StreamField((('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(help_text='With great power comes great responsibility. This HTML is unescaped. Be careful!')), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())), blank=True, null=True),
        ),
    ]
