# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-19 20:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0053_auto_20170718_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applying',
            field=wagtail.wagtailcore.fields.StreamField((('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(help_text='To add Google Analytics to your link, use this template: <a href="www.example.com" onclick="trackOutboundLink("www.example.com"); return false;">link</a>.  With great power comes great responsibility. This HTML is unescaped. Be careful!')), ('rich_text', wagtail.wagtailcore.blocks.RichTextBlock())), blank=True, null=True),
        ),
    ]
