# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0054_auto_20160925_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
