# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0055_person_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='other_info',
        ),
        migrations.AddField(
            model_name='person',
            name='blog_url',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='favorite_food',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='person',
            name='linked_in',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='person',
            name='osf_profile',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='term',
            field=models.CharField(blank=True, max_length=9, verbose_name='YEAR-YEAR'),
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
