# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0056_auto_20160925_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='term',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
