# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0057_auto_20160925_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blog_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='linked_in',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='osf_profile',
            field=models.URLField(blank=True),
        ),
    ]
