# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_auto_20171229_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='employer',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
