# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20160919_1630'),
        ('common', '0059_auto_20160925_1910'),
        ('common', '0024_auto_20160919_1604'),
    ]

    operations = [
    ]
