# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-03 21:26
from __future__ import unicode_literals

from django.apps import apps
from django.db import migrations, models
from django.db.models import F

def move_position_to_employer(apps, schema_editor):
    personModel = apps.get_model('common', 'Person')

    personModel.objects.filter(tags__slug='ambassador').update(employer=F('position'), position='')

def move_employer_to_position(apps, schema_editor):
    personModel = apps.get_model('common', 'Person')

    personModel.objects.filter(tags__slug='ambassador').update(position=F('employer'), employer='')

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0060_person_employer'),
    ]

    operations = [
        migrations.RunPython(move_position_to_employer, move_employer_to_position),
    ]
