# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-27 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0059_import_bmj_journals'),
        ('common', '0061_move_ambassador_position_to_employer'),
    ]

    operations = [
    ]
