# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_auto_20160930_1748'),
        ('common', '0072_auto_20160930_1559'),
    ]

    operations = [
    ]
