# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0073_merge_20160930_1934'),
        ('common', '0074_merge_20160930_1809'),
    ]

    operations = [
    ]
