# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0077_auto_20161004_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('background', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('responsibilities', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('skills', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('notes', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('location', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('benefits', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('applying', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('core_technologies', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('referrals', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('preferred', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('qualifications', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('experience_we_need', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
            bases=(models.Model, wagtail.wagtailsearch.index.Indexed),
        ),
    ]
