# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0078_job'),
        ('common', '0080_auto_20161005_2048'),
        ('common', '0077_auto_20161004_1744'),
    ]

    operations = [
    ]
