# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0087_auto_20161006_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='osfpage',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Footer'),
        ),
    ]
