# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0088_osfpage_footer'),
        ('common', '0084_auto_20161007_1616'),
    ]

    operations = [
    ]
