# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0089_merge_20161007_1702'),
        ('common', '0089_remove_footer_active'),
    ]

    operations = [
    ]
