# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0090_merge_20161007_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Footer'),
        ),
        migrations.AddField(
            model_name='newsindexpage',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.Footer'),
        ),
    ]
