# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0091_auto_20161007_1726'),
        ('common', '0090_auto_20161009_1950'),
    ]

    operations = [
    ]
