# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0093_auto_20161010_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OSFPage',
            new_name='CustomPage',
        ),
    ]
