<a name="job-pc"></a>
<h3>Project Coordinator</h2>
<dl class="dl-horizontal">
 <dt>Background</dt><dd><p>The Center for Open Science (COS) develops tools to support the scientific workflow (i.e., Open Science Framework), fosters community standards and efforts for open practices, and conducts metascience research -- science on scientific practices. Our best known project is the Reproducibility Project, an effort to replicate dozens of published studies in psychological science. In collaboration with the Reproducibility Initiative this project is being extended to cell biology.  We will hire someone with extremely strong social and organizational skills to help coordinate this project, and be part of our team to facilitate open science practices more broadly.</p></dd>
  <dt>Responsibilities</dt><dd><p>The key responsibilities for the replication coordinator position include: maintaining project documentation, facilitating communication and coordination of project contributors, managing project data and materials, quality control, managing project timelines and goals, and managing project research assistants. The project coordinator will also be part of the COS team to foster connections to the scientific community, communicate about COS initiatives, provide training and support for COS tools, and launch new initiatives.</p></dd>
  <dt>Skills</dt><dd><p>Extremely high social and communication skills; exceptional organization and attention to detail; ability to use web communication and documentation software effectively; team-oriented; very strong work ethic; multi-tasking; self-starter and industrious; Adaptivity to rapidly changing demands in a high performance workplace; background in scientific methodology and biology in particular (B.S. at least); effective writing skills. Skills in programming, web development, and data analysis are a plus.</p></dd>
  <dt>Notes</dt><dd><p>The Center for Open Science is an equal opportunity employer and strongly encourages applications from members of groups underrepresented in science and technology industries. The Center for Open Science (COS) is a non-profit organization based in Charlottesville, Virginia dedicated to improving the alignment between scientific values and scientific practices. Operating with a technology start-up atmosphere and mindset, the COS team moves quickly, identifies problems and creates solutions, encourages risk-taking, blends science and technology, is highly collaborative, is high energy, and is dedicated to openness.</p>
    <p>COS has three primary activities: (1) infrastructure development to support the scientific workflow (<a href="http://openscienceframework.org/">http://openscienceframework.org/</a>) - documentation, archiving, sharing, and registration - and connect with other open technologies, (2) community building among open-source developers, open science researchers, and the broader scientific community, and (3) metascience, research on scientific practices. COS is supported by the Laura and John Arnold Foundation and the Alfred P. Sloan Foundation. Get more information about COS at its <a href="http://centerforopenscience.org/">website</a>, in stories in <a href="http://www.theatlantic.com/health/archive/2012/12/the-myth-of-self-correcting-science/266228/">The Atlantic</a>, <a href="http://www.sciencemag.org/content/335/6076/1558">Science</a>, and <a href="http://www.nature.com/news/replication-studies-bad-copy-1.10634">Nature</a>, in an academic paper about the <a href="http://pps.sagepub.com/content/7/6/657.full.pdf+html">Reproducibility Project</a>, and in papers articulating a vision for "Scientific Utopia" for <a href="http://www.tandfonline.com/doi/abs/10.1080/1047840X.2012.692215#.UgK9bGTJHy0">scientific communication</a> and <a href="http://pps.sagepub.com/content/7/6/615.full">scientific practices</a>. Learn more about the <a href="https://www.scienceexchange.com/reproducibility">Reproducibility Initiative</a> from articles at <a href="http://www.nature.com/news/independent-labs-to-verify-high-profile-papers-1.11176">Nature</a>, <a href="http://www.slate.com/articles/health_and_science/science/2012/08/reproducing_scientific_studies_a_good_housekeeping_seal_of_approval_.html">Slate</a>, <a href="http://www.reuters.com/article/2012/08/14/us-science-replication-service-idUSBRE87D0I820120814">Reuters</a>, and <a href="http://www.nature.com/scibx/journal/v5/n34/full/scibx.2012.888.html">SciBX</a>.</p></dd>
  <dt>Applying</dt><dd><p>Please send a resume and cover letter explaining your background and interest in the position to jobs@centerforopenscience.org. Send with the subject heading &#8220;Project Coordinator.&#8221; Questions about the position and COS are welcome.</p></dd>
</dl>