<a name="job-omcc"></a>
<h3>Office Manager and Conference Coordinator</h3>
<dl class="dl-horizontal">
    <dt>Background</dt><dd><p>The Center for Open Science (COS) is a small team, growing fast, and needs outstanding organizational support.  We need an office manager and conference coordinator with strong skills and social savvy to provide foundational support for day-to-day operations.  We expect to host frequent visitors and coordinate multiple small conferences each year, many of which will be in Charlottesville, VA, with some being in other locations in the U.S. or other countries.  The COS team will include seven core staff, and part-time student assistants to support center activities: web infrastructure development, conferences, and research.  Staff size may double within 2-4 years.  The office manager will manage a team of assistants for conference and community-building activities.</p></dd>
    <dt>Responsibilities</dt><dd><p>Key responsibility for conference organizing including: arranging and managing meeting space, scheduling, travel, food, accommodations, and general guest support.  On-site coordination of events.  Point-of-contact for COS visitors, affiliates, board members, and general inquires.  Manages office administrative functions: facilities, food, scheduling, procurement, insurance, payroll, paperwork, reimbursements, reception, travel.  Supervises administrative assistants.  Creates and maintains office procedures.  Provides general administrative support to directors.  Maintains flexibility for ad hoc projects as needs arise in this high energy, start-up environment.</p></dd>
    <dt>Skills</dt><dd><p>Very high social competency and communication skills, service-oriented style, very strong work ethic, can work independently, strong organizational skills, effective management with assistants and support personnel, strong negotiation skills, multi-tasking, and effective real-time decision making.  Appreciation for science and technology a plus.</p></dd>
    <dt>Notes</dt><dd><p>The Center for Open Science is an equal opportunity employer and strongly encourages applications from members of groups underrepresented in science and technology industries.  The Center for Open Science (COS) is a non-profit organization based in Charlottesville, Virginia dedicated to improving the alignment between scientific values and scientific practices.  Get more information about COS goals and activities at http://centerforopenscience.org/.</p></dd>
    <dt>Applying</dt><dd><p>Please send a resume and cover letter explaining your background and interest in the position to <a href="mailto:jobs@centerforopenscience.org">jobs@centerforopenscience.org</a>.  Send with the subject heading "Office guru".  Questions about the position and COS are welcome.</p></dd>
</dl>
