# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='author_pages', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
