# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20161012_1628'),
        ('blog', '0005_auto_20161012_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPagePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.Person')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpageperson',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.BlogPage'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='authors',
            field=models.ManyToManyField(blank=True, through='blog.BlogPagePerson', to='common.Person'),
        ),
    ]
