# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 02:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161013_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='authors',
            new_name='blog_authors',
        ),
        migrations.AlterField(
            model_name='blogpageperson',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blog.BlogPage'),
        ),
    ]
