# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161013_0223'),
        ('blog', '0006_auto_20161012_1555'),
        ('blog', '0002_auto_20161013_1518'),
    ]

    operations = [
    ]
