# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20161017_1323'),
        ('blog', '0011_blogpage_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='footer',
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='common.Footer'),
        ),
    ]
