# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161017_1801'),
        ('blog', '0012_blogindexpage_footer'),
    ]

    operations = [
    ]
