# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161013_2112'),
        ('blog', '0012_blogindexpage_footer'),
    ]

    operations = [
    ]
