# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_merge_20161017_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
    ]
