# -*- coding: utf-8 -*-		
# Generated by Django 1.10.2 on 2016-10-19 17:41		
from __future__ import unicode_literals		
		
from django.db import migrations		
		
		
class Migration(migrations.Migration):		
		
    dependencies = [		
        ('blog', '0015_merge_20161018_2019'),		
    ]		
		
    operations = [		
        migrations.RemoveField(		
            model_name='blogpage',		
            name='author',		
        ),		
    ]
