# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 18:01
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('common', '0053_auto_20170718_1801'),
        ('blog', '0021_auto_20161115_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='common.PageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
